// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/26/2026, 9:31:53 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/julatonedwinv/projects/ptt-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/julatonedwinv/projects/ptt-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/julatonedwinv/projects/ptt-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/julatonedwinv/projects/ptt-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/julatonedwinv/projects/ptt-website/plugins/**/*.{js,ts,mjs}","/Users/julatonedwinv/projects/ptt-website/composables/**/*.{js,ts,mjs}","/Users/julatonedwinv/projects/ptt-website/utils/**/*.{js,ts,mjs}","/Users/julatonedwinv/projects/ptt-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/julatonedwinv/projects/ptt-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/julatonedwinv/projects/ptt-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/julatonedwinv/projects/ptt-website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;